# Generated by Django 3.2.8 on 2021-12-03 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Acesso',
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(choices=[('professor', 'professor'), ('secretaria', 'secretaria'), ('coordenacao', 'coordenacao')], max_length=50)),
                ('nome', models.CharField(max_length=30)),
                ('snome', models.CharField(max_length=30, verbose_name='sobrenome')),
                ('avatar', models.ImageField(blank=True, upload_to='avatar')),
                ('assinatura', models.CharField(max_length=30)),
                ('nivel', models.CharField(choices=[('EF', 'fundamental'), ('EM', 'Médio')], max_length=30)),
                ('disciplina', models.CharField(choices=[('artes', 'artes'), ('ciencias', 'ciências'), ('ed.fisica', 'educação física'), ('geografia', 'geografia'), ('historia', 'história'), ('ingles', 'inglês'), ('portugues', 'lingua portuguesa'), ('matematica', 'matemática'), ('artesm', 'artes médio'), ('biologia', 'biologia'), ('ed.fisicam', 'educação física médio'), ('espanhol', 'espanhol'), ('filosofia', 'filosofia'), ('fisica', 'física'), ('geografiam', 'geografia médio'), ('historiam', 'história médio'), ('inglesm', 'inglês médio '), ('portuguesm', 'lingua portuguesa médio'), ('matematicam', 'matemática médio'), ('quimica', 'química'), ('sociologia', 'sociologia')], max_length=30)),
                ('turno', models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite')], max_length=30)),
                ('acesso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario_prof.acesso')),
            ],
            options={
                'verbose_name': 'Docente',
            },
        ),
    ]
