# Generated by Django 3.2.8 on 2021-11-28 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario_prof', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acesso',
            options={'verbose_name': 'Acesso'},
        ),
        migrations.RenameField(
            model_name='acesso',
            old_name='nome',
            new_name='usuario',
        ),
    ]
