# Generated by Django 3.2.8 on 2021-11-28 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario_prof', '0003_rename_usuario_acesso_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acesso',
            old_name='nome',
            new_name='profID',
        ),
    ]
