# Generated by Django 3.2.8 on 2021-11-28 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario_prof', '0004_rename_nome_acesso_profid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acesso',
            old_name='profID',
            new_name='nome',
        ),
    ]
