# Generated by Django 3.2.8 on 2021-12-11 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgendamentoInicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcao', models.CharField(choices=[('fundamental', 'Fundamental'), ('medio', 'Médio')], max_length=11, verbose_name='Selecione nível')),
            ],
            options={
                'verbose_name': 'Nivel',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profF', models.CharField(choices=[], max_length=20, verbose_name='professores Fundamental(as)')),
                ('profM', models.CharField(choices=[], max_length=20, verbose_name='professores Médio(as)')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.nivel')),
            ],
            options={
                'verbose_name': 'Professor',
            },
        ),
        migrations.CreateModel(
            name='Disciplinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dF', models.CharField(choices=[], max_length=20, verbose_name='Disciplinas do Fundamental')),
                ('dM', models.CharField(choices=[], max_length=20, verbose_name='Disciplinas do Médio')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.nivel')),
            ],
            options={
                'verbose_name': 'Disciplinas',
            },
        ),
    ]
