# Generated by Django 3.2.5 on 2021-10-13 12:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgendamentoAln',
            fields=[
                ('nome', models.CharField(max_length=20)),
                ('sobrenome', models.CharField(max_length=20)),
                ('matricula', models.IntegerField()),
                ('turno', models.CharField(choices=[('manhã', 'manhã'), ('tarde', 'tarde'), ('noite', 'noite')], max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('cell', models.IntegerField(verbose_name='celular')),
                ('protocolo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='insira novamento sua matricula (somente numeros)')),
                ('criado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-criado',),
            },
        ),
        migrations.CreateModel(
            name='AgendamentoPRF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor', models.CharField(choices=[('carlos', 'carlos'), ('helda', 'helda'), ('ilma', 'ilma'), ('barbara', 'barbara')], max_length=20, verbose_name='professores(as)')),
                ('AgendamentoAln', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.agendamentoaln')),
            ],
        ),
        migrations.CreateModel(
            name='AgendamentoNVL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('Fundamental', 'Fundamental'), ('Médio', 'Médio')], max_length=20)),
                ('AgendamentoAln', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.agendamentoaln')),
            ],
        ),
        migrations.CreateModel(
            name='AgendamentoDSC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dF', models.CharField(choices=[('Selecione', 'Selecione'), ('Artes', 'Artes'), ('Ciências', 'Ciências'), ('Ed.Fisica', 'Ed.Fisica'), ('Geografia', 'Geografia'), ('História', 'História'), ('Inglês', 'Inglês'), ('Matemática', 'Matemática'), ('Português', 'Português')], max_length=20, verbose_name='Disciplinas do Fundamental')),
                ('dM', models.CharField(choices=[('Selecione', 'Selecione'), ('Artes', 'Artes'), ('Biologia', 'Biologia'), ('Ed.Fisica', 'Ed.Fisica'), ('Espanhol', 'Espanhol'), ('Filosofia', 'Filosofia'), ('Geografia', 'Geografia'), ('História', 'História'), ('Inglês', 'Inglês'), ('Matemática', 'Matemática'), ('Português', 'Português'), ('Quimica', 'Quimica'), ('Sociologia', 'Sociologia')], max_length=20, verbose_name='Disciplinas do Médio')),
                ('AgendamentoAln', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.agendamentoaln')),
            ],
        ),
    ]
