# Generated by Django 3.2.8 on 2021-12-20 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgendamentoInicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disc', models.CharField(max_length=20, verbose_name='Disciplinas')),
            ],
            options={
                'verbose_name': 'Disciplinas',
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcaof', models.CharField(max_length=11)),
            ],
            options={
                'verbose_name': 'Nivel',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.CharField(max_length=20)),
                ('turno', models.CharField(max_length=20)),
                ('docente', models.CharField(max_length=20)),
                ('disc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.disciplinas')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.nivel')),
            ],
            options={
                'verbose_name': 'Professor',
            },
        ),
        migrations.AddField(
            model_name='disciplinas',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.nivel'),
        ),
    ]
