# Generated by Django 3.2.8 on 2021-11-24 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcao', models.CharField(choices=[('Fd', 'Fundamental'), ('Md', 'Médio')], max_length=11, verbose_name='Selecione nível')),
            ],
            options={
                'verbose_name': 'Disciplinas',
            },
        ),
    ]
