# Generated by Django 3.2.8 on 2021-11-04 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.FileField(blank=True, upload_to='avatar')),
                ('dochist', models.FileField(blank=True, upload_to='historico')),
                ('docRG', models.FileField(blank=True, upload_to='rg')),
                ('docRG2', models.FileField(blank=True, upload_to='rg')),
                ('docCPF', models.FileField(blank=True, upload_to='cpf')),
                ('docRes', models.FileField(blank=True, upload_to='comprovaResid')),
                ('docCert', models.FileField(blank=True, upload_to='certificaFund')),
                ('matric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.matricula')),
            ],
            options={
                'verbose_name': 'Imagens',
            },
        ),
    ]
