# Generated by Django 3.2.8 on 2021-11-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_usr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docpessoal',
            name='cpf',
            field=models.CharField(max_length=11, verbose_name='C.P.F.'),
        ),
        migrations.AlterField(
            model_name='docpessoal',
            name='rg',
            field=models.CharField(max_length=20, verbose_name='R.G.'),
        ),
    ]
